#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: smartcodinghub

# Short bio or description (displayed in the header)
description: A blog about smart coding.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar:

#
# Flags below are optional
#

#Pagination
paginate: 10
paginate_path: "/posts/:num"

#Read More
excerpt_separator: "<!--more-->"

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: smartcodinghub@gmail.com
  facebook:
  flickr:
  github: smartcodinghub
  instagram:
  linkedin:
  pinterest:
  rss: http://smartcodinghub.github.io/images/rss.png
  twitter:
  stackoverflow: users/4813378/oscar-vicente-perez
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: smartcodinghub

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "https://smartcodinghub.com"
enforce_ssl: smartcodinghub.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

highlighter: rouge
markdown: kramdown

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  input: GFM

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - config.txt
